column FIRST_NAME heading 'First Name';
column LAST_NAME heading 'Last Name';
column EMPLOYEE_ID heading 'Employee ID' format a11;
column ADDRESS_ID heading 'Address_ID' format a10;
column STREET heading 'Street';
column CITY heading 'City';
column STATE heading 'State';
column COUNTRY heading 'Country';
column ZIPCODE heading 'Zipcode' format a7;
column PHONE_NUMBER heading 'Phone|Number';
column JOB_ID heading 'Job ID';
column DEPARTMENT heading 'Department';
column SALARY heading 'Monthly|Salary' format $999,999.99;
column PACKAGE_ID heading 'Package ID' format a10;
column CUSTOMER_ID heading 'Customer ID' format a11;
column TYPE heading 'Package|Type' format a7;
column PRICE heading 'Price' format $99.99;
column DEMOGRAPHICS_ID heading 'Demographics ID' format a15;
column GENDER heading 'Gender' format a6;
column ETHNICITY heading 'Ethnicity' format a9;
column MARRIAGE_STATUS heading 'Marriage|Status' format a8;
set underline =;