CREATE TABLE customer_packages
(
	PACKAGE_ID VARCHAR(5) NOT NULL PRIMARY KEY,
	TYPE VARCHAR(6) NOT NULL,
	PRICE float NOT NULL
);

create table customer_data
(
	CUSTOMER_ID VARCHAR(8) NOT NULL PRIMARY KEY,
	PACKAGE_ID VARCHAR(5) NOT NULL,
	FIRST_NAME VARCHAR(15) NOT NULL,
	LAST_NAME VARCHAR(15) NOT NULL,
	CONSTRAINT fk_packageID FOREIGN KEY (PACKAGE_ID)
	REFERENCES customer_packages(PACKAGE_ID)
);

create table customer_address_data
(
	ADDRESS_ID VARCHAR(8) NOT NULL PRIMARY KEY,
	CUSTOMER_ID VARCHAR(8) NOT NULL,
	STREET VARCHAR(25) NOT NULL,
	CITY VARCHAR(11) NOT NULL,
	STATE VARCHAR(13) NOT NULL,
	COUNTRY varchar(13) NOT NULL,
	ZIPCODE VARCHAR(5) NOT NULL,
	PHONE_NUMBER VARCHAR(13),
	CONSTRAINT fk_customerID FOREIGN KEY (CUSTOMER_ID)
	REFERENCES customer_data(CUSTOMER_ID)
);

CREATE TABLE customer_demographics
(
	DEMOGRAPHICS_ID VARCHAR(8) NOT NULL PRIMARY KEY,
	CUSTOMER_ID VARCHAR(8) NOT NULL,
	GENDER VARCHAR(6),
	ETHNICITY VARCHAR(5),
	MARRIAGE_STATUS VARCHAR(3),
	FOREIGN KEY (CUSTOMER_ID)
	REFERENCES customer_data(CUSTOMER_ID)
);