INSERT INTO customer_packages (PACKAGE_ID, TYPE, PRICE)VALUES ('PCK_1', 'GOLD', 14.99);
INSERT INTO customer_packages (PACKAGE_ID, TYPE, PRICE)VALUES ('PCK_2', 'SILVER', 9.99);
INSERT INTO customer_packages (PACKAGE_ID, TYPE, PRICE)VALUES ('PCK_3', 'BRONZE', 4.99);